/* automatically generated by rust-bindgen 0.68.1 */
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub const ASICAMERA_ID_MAX: u32 = 256;
pub const ASI_BAYER_PATTERN_ASI_BAYER_RG: ASI_BAYER_PATTERN = 0;
pub const ASI_BAYER_PATTERN_ASI_BAYER_BG: ASI_BAYER_PATTERN = 1;
pub const ASI_BAYER_PATTERN_ASI_BAYER_GR: ASI_BAYER_PATTERN = 2;
pub const ASI_BAYER_PATTERN_ASI_BAYER_GB: ASI_BAYER_PATTERN = 3;
pub type ASI_BAYER_PATTERN = ::std::os::raw::c_uint;
pub const ASI_IMG_TYPE_ASI_IMG_RAW8: ASI_IMG_TYPE = 0;
pub const ASI_IMG_TYPE_ASI_IMG_RGB24: ASI_IMG_TYPE = 1;
pub const ASI_IMG_TYPE_ASI_IMG_RAW16: ASI_IMG_TYPE = 2;
pub const ASI_IMG_TYPE_ASI_IMG_Y8: ASI_IMG_TYPE = 3;
pub const ASI_IMG_TYPE_ASI_IMG_END: ASI_IMG_TYPE = -1;
pub type ASI_IMG_TYPE = ::std::os::raw::c_int;
pub const ASI_GUIDE_DIRECTION_ASI_GUIDE_NORTH: ASI_GUIDE_DIRECTION = 0;
pub const ASI_GUIDE_DIRECTION_ASI_GUIDE_SOUTH: ASI_GUIDE_DIRECTION = 1;
pub const ASI_GUIDE_DIRECTION_ASI_GUIDE_EAST: ASI_GUIDE_DIRECTION = 2;
pub const ASI_GUIDE_DIRECTION_ASI_GUIDE_WEST: ASI_GUIDE_DIRECTION = 3;
pub type ASI_GUIDE_DIRECTION = ::std::os::raw::c_uint;
pub const ASI_FLIP_STATUS_ASI_FLIP_NONE: ASI_FLIP_STATUS = 0;
pub const ASI_FLIP_STATUS_ASI_FLIP_HORIZ: ASI_FLIP_STATUS = 1;
pub const ASI_FLIP_STATUS_ASI_FLIP_VERT: ASI_FLIP_STATUS = 2;
pub const ASI_FLIP_STATUS_ASI_FLIP_BOTH: ASI_FLIP_STATUS = 3;
pub type ASI_FLIP_STATUS = ::std::os::raw::c_uint;
pub const ASI_CAMERA_MODE_ASI_MODE_NORMAL: ASI_CAMERA_MODE = 0;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_SOFT_EDGE: ASI_CAMERA_MODE = 1;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_RISE_EDGE: ASI_CAMERA_MODE = 2;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_FALL_EDGE: ASI_CAMERA_MODE = 3;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_SOFT_LEVEL: ASI_CAMERA_MODE = 4;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_HIGH_LEVEL: ASI_CAMERA_MODE = 5;
pub const ASI_CAMERA_MODE_ASI_MODE_TRIG_LOW_LEVEL: ASI_CAMERA_MODE = 6;
pub const ASI_CAMERA_MODE_ASI_MODE_END: ASI_CAMERA_MODE = -1;
pub type ASI_CAMERA_MODE = ::std::os::raw::c_int;
pub const ASI_TRIG_OUTPUT_ASI_TRIG_OUTPUT_PINA: ASI_TRIG_OUTPUT = 0;
pub const ASI_TRIG_OUTPUT_ASI_TRIG_OUTPUT_PINB: ASI_TRIG_OUTPUT = 1;
pub const ASI_TRIG_OUTPUT_ASI_TRIG_OUTPUT_NONE: ASI_TRIG_OUTPUT = -1;
pub type ASI_TRIG_OUTPUT = ::std::os::raw::c_int;
pub use self::ASI_TRIG_OUTPUT as ASI_TRIG_OUTPUT_PIN;
pub const ASI_ERROR_CODE_ASI_SUCCESS: ASI_ERROR_CODE = 0;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_INDEX: ASI_ERROR_CODE = 1;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_ID: ASI_ERROR_CODE = 2;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_CONTROL_TYPE: ASI_ERROR_CODE = 3;
pub const ASI_ERROR_CODE_ASI_ERROR_CAMERA_CLOSED: ASI_ERROR_CODE = 4;
pub const ASI_ERROR_CODE_ASI_ERROR_CAMERA_REMOVED: ASI_ERROR_CODE = 5;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_PATH: ASI_ERROR_CODE = 6;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_FILEFORMAT: ASI_ERROR_CODE = 7;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_SIZE: ASI_ERROR_CODE = 8;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_IMGTYPE: ASI_ERROR_CODE = 9;
pub const ASI_ERROR_CODE_ASI_ERROR_OUTOF_BOUNDARY: ASI_ERROR_CODE = 10;
pub const ASI_ERROR_CODE_ASI_ERROR_TIMEOUT: ASI_ERROR_CODE = 11;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_SEQUENCE: ASI_ERROR_CODE = 12;
pub const ASI_ERROR_CODE_ASI_ERROR_BUFFER_TOO_SMALL: ASI_ERROR_CODE = 13;
pub const ASI_ERROR_CODE_ASI_ERROR_VIDEO_MODE_ACTIVE: ASI_ERROR_CODE = 14;
pub const ASI_ERROR_CODE_ASI_ERROR_EXPOSURE_IN_PROGRESS: ASI_ERROR_CODE = 15;
pub const ASI_ERROR_CODE_ASI_ERROR_GENERAL_ERROR: ASI_ERROR_CODE = 16;
pub const ASI_ERROR_CODE_ASI_ERROR_INVALID_MODE: ASI_ERROR_CODE = 17;
pub const ASI_ERROR_CODE_ASI_ERROR_GPS_NOT_SUPPORTED: ASI_ERROR_CODE = 18;
pub const ASI_ERROR_CODE_ASI_ERROR_GPS_VER_ERR: ASI_ERROR_CODE = 19;
pub const ASI_ERROR_CODE_ASI_ERROR_GPS_FPGA_ERR: ASI_ERROR_CODE = 20;
pub const ASI_ERROR_CODE_ASI_ERROR_GPS_PARAM_OUT_OF_RANGE: ASI_ERROR_CODE = 21;
pub const ASI_ERROR_CODE_ASI_ERROR_GPS_DATA_INVALID: ASI_ERROR_CODE = 22;
pub const ASI_ERROR_CODE_ASI_ERROR_END: ASI_ERROR_CODE = 23;
pub type ASI_ERROR_CODE = ::std::os::raw::c_uint;
pub const ASI_BOOL_ASI_FALSE: ASI_BOOL = 0;
pub const ASI_BOOL_ASI_TRUE: ASI_BOOL = 1;
pub type ASI_BOOL = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_CAMERA_INFO {
    pub Name: [::std::os::raw::c_char; 64usize],
    pub CameraID: ::std::os::raw::c_int,
    pub MaxHeight: ::std::os::raw::c_long,
    pub MaxWidth: ::std::os::raw::c_long,
    pub IsColorCam: ASI_BOOL,
    pub BayerPattern: ASI_BAYER_PATTERN,
    pub SupportedBins: [::std::os::raw::c_int; 16usize],
    pub SupportedVideoFormat: [ASI_IMG_TYPE; 8usize],
    pub PixelSize: f64,
    pub MechanicalShutter: ASI_BOOL,
    pub ST4Port: ASI_BOOL,
    pub IsCoolerCam: ASI_BOOL,
    pub IsUSB3Host: ASI_BOOL,
    pub IsUSB3Camera: ASI_BOOL,
    pub ElecPerADU: f32,
    pub BitDepth: ::std::os::raw::c_int,
    pub IsTriggerCam: ASI_BOOL,
    pub Unused: [::std::os::raw::c_char; 16usize],
}
#[test]
fn bindgen_test_layout__ASI_CAMERA_INFO() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_CAMERA_INFO> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_CAMERA_INFO>(),
        248usize,
        concat!("Size of: ", stringify!(_ASI_CAMERA_INFO))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_CAMERA_INFO>(),
        8usize,
        concat!("Alignment of ", stringify!(_ASI_CAMERA_INFO))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(Name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).CameraID) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(CameraID)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MaxHeight) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(MaxHeight)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MaxWidth) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(MaxWidth)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsColorCam) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(IsColorCam)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).BayerPattern) as usize - ptr as usize },
        92usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(BayerPattern)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SupportedBins) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(SupportedBins)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SupportedVideoFormat) as usize - ptr as usize },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(SupportedVideoFormat)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).PixelSize) as usize - ptr as usize },
        192usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(PixelSize)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MechanicalShutter) as usize - ptr as usize },
        200usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(MechanicalShutter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ST4Port) as usize - ptr as usize },
        204usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(ST4Port)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsCoolerCam) as usize - ptr as usize },
        208usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(IsCoolerCam)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsUSB3Host) as usize - ptr as usize },
        212usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(IsUSB3Host)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsUSB3Camera) as usize - ptr as usize },
        216usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(IsUSB3Camera)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ElecPerADU) as usize - ptr as usize },
        220usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(ElecPerADU)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).BitDepth) as usize - ptr as usize },
        224usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(BitDepth)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsTriggerCam) as usize - ptr as usize },
        228usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(IsTriggerCam)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Unused) as usize - ptr as usize },
        232usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CAMERA_INFO),
            "::",
            stringify!(Unused)
        )
    );
}
pub type ASI_CAMERA_INFO = _ASI_CAMERA_INFO;
pub const ASI_CONTROL_TYPE_ASI_GAIN: ASI_CONTROL_TYPE = 0;
pub const ASI_CONTROL_TYPE_ASI_EXPOSURE: ASI_CONTROL_TYPE = 1;
pub const ASI_CONTROL_TYPE_ASI_GAMMA: ASI_CONTROL_TYPE = 2;
pub const ASI_CONTROL_TYPE_ASI_WB_R: ASI_CONTROL_TYPE = 3;
pub const ASI_CONTROL_TYPE_ASI_WB_B: ASI_CONTROL_TYPE = 4;
pub const ASI_CONTROL_TYPE_ASI_OFFSET: ASI_CONTROL_TYPE = 5;
pub const ASI_CONTROL_TYPE_ASI_BANDWIDTHOVERLOAD: ASI_CONTROL_TYPE = 6;
pub const ASI_CONTROL_TYPE_ASI_OVERCLOCK: ASI_CONTROL_TYPE = 7;
pub const ASI_CONTROL_TYPE_ASI_TEMPERATURE: ASI_CONTROL_TYPE = 8;
pub const ASI_CONTROL_TYPE_ASI_FLIP: ASI_CONTROL_TYPE = 9;
pub const ASI_CONTROL_TYPE_ASI_AUTO_MAX_GAIN: ASI_CONTROL_TYPE = 10;
pub const ASI_CONTROL_TYPE_ASI_AUTO_MAX_EXP: ASI_CONTROL_TYPE = 11;
pub const ASI_CONTROL_TYPE_ASI_AUTO_TARGET_BRIGHTNESS: ASI_CONTROL_TYPE = 12;
pub const ASI_CONTROL_TYPE_ASI_HARDWARE_BIN: ASI_CONTROL_TYPE = 13;
pub const ASI_CONTROL_TYPE_ASI_HIGH_SPEED_MODE: ASI_CONTROL_TYPE = 14;
pub const ASI_CONTROL_TYPE_ASI_COOLER_POWER_PERC: ASI_CONTROL_TYPE = 15;
pub const ASI_CONTROL_TYPE_ASI_TARGET_TEMP: ASI_CONTROL_TYPE = 16;
pub const ASI_CONTROL_TYPE_ASI_COOLER_ON: ASI_CONTROL_TYPE = 17;
pub const ASI_CONTROL_TYPE_ASI_MONO_BIN: ASI_CONTROL_TYPE = 18;
pub const ASI_CONTROL_TYPE_ASI_FAN_ON: ASI_CONTROL_TYPE = 19;
pub const ASI_CONTROL_TYPE_ASI_PATTERN_ADJUST: ASI_CONTROL_TYPE = 20;
pub const ASI_CONTROL_TYPE_ASI_ANTI_DEW_HEATER: ASI_CONTROL_TYPE = 21;
pub const ASI_CONTROL_TYPE_ASI_FAN_ADJUST: ASI_CONTROL_TYPE = 22;
pub const ASI_CONTROL_TYPE_ASI_PWRLED_BRIGNT: ASI_CONTROL_TYPE = 23;
pub const ASI_CONTROL_TYPE_ASI_USBHUB_RESET: ASI_CONTROL_TYPE = 24;
pub const ASI_CONTROL_TYPE_ASI_GPS_SUPPORT: ASI_CONTROL_TYPE = 25;
pub const ASI_CONTROL_TYPE_ASI_GPS_START_LINE: ASI_CONTROL_TYPE = 26;
pub const ASI_CONTROL_TYPE_ASI_GPS_END_LINE: ASI_CONTROL_TYPE = 27;
pub const ASI_CONTROL_TYPE_ASI_ROLLING_INTERVAL: ASI_CONTROL_TYPE = 28;
pub type ASI_CONTROL_TYPE = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_CONTROL_CAPS {
    pub Name: [::std::os::raw::c_char; 64usize],
    pub Description: [::std::os::raw::c_char; 128usize],
    pub MaxValue: ::std::os::raw::c_long,
    pub MinValue: ::std::os::raw::c_long,
    pub DefaultValue: ::std::os::raw::c_long,
    pub IsAutoSupported: ASI_BOOL,
    pub IsWritable: ASI_BOOL,
    pub ControlType: ASI_CONTROL_TYPE,
    pub Unused: [::std::os::raw::c_char; 32usize],
}
#[test]
fn bindgen_test_layout__ASI_CONTROL_CAPS() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_CONTROL_CAPS> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_CONTROL_CAPS>(),
        264usize,
        concat!("Size of: ", stringify!(_ASI_CONTROL_CAPS))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_CONTROL_CAPS>(),
        8usize,
        concat!("Alignment of ", stringify!(_ASI_CONTROL_CAPS))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(Name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Description) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(Description)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MaxValue) as usize - ptr as usize },
        192usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(MaxValue)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MinValue) as usize - ptr as usize },
        200usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(MinValue)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).DefaultValue) as usize - ptr as usize },
        208usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(DefaultValue)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsAutoSupported) as usize - ptr as usize },
        216usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(IsAutoSupported)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsWritable) as usize - ptr as usize },
        220usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(IsWritable)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ControlType) as usize - ptr as usize },
        224usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(ControlType)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Unused) as usize - ptr as usize },
        228usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_CONTROL_CAPS),
            "::",
            stringify!(Unused)
        )
    );
}
pub type ASI_CONTROL_CAPS = _ASI_CONTROL_CAPS;
pub const ASI_EXPOSURE_STATUS_ASI_EXP_IDLE: ASI_EXPOSURE_STATUS = 0;
pub const ASI_EXPOSURE_STATUS_ASI_EXP_WORKING: ASI_EXPOSURE_STATUS = 1;
pub const ASI_EXPOSURE_STATUS_ASI_EXP_SUCCESS: ASI_EXPOSURE_STATUS = 2;
pub const ASI_EXPOSURE_STATUS_ASI_EXP_FAILED: ASI_EXPOSURE_STATUS = 3;
pub type ASI_EXPOSURE_STATUS = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_ID {
    pub id: [::std::os::raw::c_uchar; 8usize],
}
#[test]
fn bindgen_test_layout__ASI_ID() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_ID> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_ID>(),
        8usize,
        concat!("Size of: ", stringify!(_ASI_ID))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_ID>(),
        1usize,
        concat!("Alignment of ", stringify!(_ASI_ID))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_ID),
            "::",
            stringify!(id)
        )
    );
}
pub type ASI_ID = _ASI_ID;
pub type ASI_SN = ASI_ID;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_SUPPORTED_MODE {
    pub SupportedCameraMode: [ASI_CAMERA_MODE; 16usize],
}
#[test]
fn bindgen_test_layout__ASI_SUPPORTED_MODE() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_SUPPORTED_MODE> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_SUPPORTED_MODE>(),
        64usize,
        concat!("Size of: ", stringify!(_ASI_SUPPORTED_MODE))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_SUPPORTED_MODE>(),
        4usize,
        concat!("Alignment of ", stringify!(_ASI_SUPPORTED_MODE))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SupportedCameraMode) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_SUPPORTED_MODE),
            "::",
            stringify!(SupportedCameraMode)
        )
    );
}
pub type ASI_SUPPORTED_MODE = _ASI_SUPPORTED_MODE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_DATE_TIME {
    pub Year: ::std::os::raw::c_int,
    pub Month: ::std::os::raw::c_int,
    pub Day: ::std::os::raw::c_int,
    pub Hour: ::std::os::raw::c_int,
    pub Minute: ::std::os::raw::c_int,
    pub Second: ::std::os::raw::c_int,
    pub Msecond: ::std::os::raw::c_int,
    pub Usecond: ::std::os::raw::c_int,
    pub Unused: [::std::os::raw::c_char; 64usize],
}
#[test]
fn bindgen_test_layout__ASI_DATE_TIME() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_DATE_TIME> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_DATE_TIME>(),
        96usize,
        concat!("Size of: ", stringify!(_ASI_DATE_TIME))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_DATE_TIME>(),
        4usize,
        concat!("Alignment of ", stringify!(_ASI_DATE_TIME))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Year) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Year)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Month) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Month)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Day) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Day)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Hour) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Hour)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Minute) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Minute)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Second) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Second)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Msecond) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Msecond)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Usecond) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Usecond)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Unused) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_DATE_TIME),
            "::",
            stringify!(Unused)
        )
    );
}
pub type ASI_DATE_TIME = _ASI_DATE_TIME;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ASI_GPS_DATA {
    pub Datetime: ASI_DATE_TIME,
    pub Latitude: f64,
    pub Longitude: f64,
    pub Altitude: ::std::os::raw::c_int,
    pub SatelliteNum: ::std::os::raw::c_int,
    pub Unused: [::std::os::raw::c_char; 64usize],
}
#[test]
fn bindgen_test_layout__ASI_GPS_DATA() {
    const UNINIT: ::std::mem::MaybeUninit<_ASI_GPS_DATA> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_ASI_GPS_DATA>(),
        184usize,
        concat!("Size of: ", stringify!(_ASI_GPS_DATA))
    );
    assert_eq!(
        ::std::mem::align_of::<_ASI_GPS_DATA>(),
        8usize,
        concat!("Alignment of ", stringify!(_ASI_GPS_DATA))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Datetime) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(Datetime)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Latitude) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(Latitude)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Longitude) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(Longitude)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Altitude) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(Altitude)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SatelliteNum) as usize - ptr as usize },
        116usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(SatelliteNum)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Unused) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(_ASI_GPS_DATA),
            "::",
            stringify!(Unused)
        )
    );
}
pub type ASI_GPS_DATA = _ASI_GPS_DATA;
extern "C" {
    pub fn ASIGetNumOfConnectedCameras() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetProductIDs(pPIDs: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASICameraCheck(
        iVID: ::std::os::raw::c_int,
        iPID: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetCameraProperty(
        pASICameraInfo: *mut ASI_CAMERA_INFO,
        iCameraIndex: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetCameraPropertyByID(
        iCameraID: ::std::os::raw::c_int,
        pASICameraInfo: *mut ASI_CAMERA_INFO,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIOpenCamera(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIInitCamera(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASICloseCamera(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetNumOfControls(
        iCameraID: ::std::os::raw::c_int,
        piNumberOfControls: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetControlCaps(
        iCameraID: ::std::os::raw::c_int,
        iControlIndex: ::std::os::raw::c_int,
        pControlCaps: *mut ASI_CONTROL_CAPS,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetControlValue(
        iCameraID: ::std::os::raw::c_int,
        ControlType: ::std::os::raw::c_int,
        plValue: *mut ::std::os::raw::c_long,
        pbAuto: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetControlValue(
        iCameraID: ::std::os::raw::c_int,
        ControlType: ::std::os::raw::c_int,
        lValue: ::std::os::raw::c_long,
        bAuto: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetROIFormat(
        iCameraID: ::std::os::raw::c_int,
        iWidth: ::std::os::raw::c_int,
        iHeight: ::std::os::raw::c_int,
        iBin: ::std::os::raw::c_int,
        Img_type: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetROIFormat(
        iCameraID: ::std::os::raw::c_int,
        piWidth: *mut ::std::os::raw::c_int,
        piHeight: *mut ::std::os::raw::c_int,
        piBin: *mut ::std::os::raw::c_int,
        pImg_type: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetStartPos(
        iCameraID: ::std::os::raw::c_int,
        iStartX: ::std::os::raw::c_int,
        iStartY: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetStartPos(
        iCameraID: ::std::os::raw::c_int,
        piStartX: *mut ::std::os::raw::c_int,
        piStartY: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetDroppedFrames(
        iCameraID: ::std::os::raw::c_int,
        piDropFrames: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIEnableDarkSubtract(
        iCameraID: ::std::os::raw::c_int,
        pcBMPPath: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIDisableDarkSubtract(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIStartVideoCapture(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIStopVideoCapture(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetVideoData(
        iCameraID: ::std::os::raw::c_int,
        pBuffer: *mut ::std::os::raw::c_uchar,
        lBuffSize: ::std::os::raw::c_long,
        iWaitms: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetVideoDataGPS(
        iCameraID: ::std::os::raw::c_int,
        pBuffer: *mut ::std::os::raw::c_uchar,
        lBuffSize: ::std::os::raw::c_long,
        iWaitms: ::std::os::raw::c_int,
        gpsData: *mut ASI_GPS_DATA,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIPulseGuideOn(
        iCameraID: ::std::os::raw::c_int,
        direction: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIPulseGuideOff(
        iCameraID: ::std::os::raw::c_int,
        direction: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIStartExposure(
        iCameraID: ::std::os::raw::c_int,
        bIsDark: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIStopExposure(iCameraID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetExpStatus(
        iCameraID: ::std::os::raw::c_int,
        pExpStatus: *mut ASI_EXPOSURE_STATUS,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetDataAfterExp(
        iCameraID: ::std::os::raw::c_int,
        pBuffer: *mut ::std::os::raw::c_uchar,
        lBuffSize: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetDataAfterExpGPS(
        iCameraID: ::std::os::raw::c_int,
        pBuffer: *mut ::std::os::raw::c_uchar,
        lBuffSize: ::std::os::raw::c_long,
        gpsData: *mut ASI_GPS_DATA,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetID(iCameraID: ::std::os::raw::c_int, pID: *mut ASI_ID) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetID(iCameraID: ::std::os::raw::c_int, ID: ASI_ID) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetGainOffset(
        iCameraID: ::std::os::raw::c_int,
        pOffset_HighestDR: *mut ::std::os::raw::c_int,
        pOffset_UnityGain: *mut ::std::os::raw::c_int,
        pGain_LowestRN: *mut ::std::os::raw::c_int,
        pOffset_LowestRN: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetLMHGainOffset(
        iCameraID: ::std::os::raw::c_int,
        pLGain: *mut ::std::os::raw::c_int,
        pMGain: *mut ::std::os::raw::c_int,
        pHGain: *mut ::std::os::raw::c_int,
        pHOffset: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetSDKVersion() -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ASIGetCameraSupportMode(
        iCameraID: ::std::os::raw::c_int,
        pSupportedMode: *mut ASI_SUPPORTED_MODE,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetCameraMode(
        iCameraID: ::std::os::raw::c_int,
        mode: *mut ASI_CAMERA_MODE,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetCameraMode(
        iCameraID: ::std::os::raw::c_int,
        mode: ASI_CAMERA_MODE,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISendSoftTrigger(
        iCameraID: ::std::os::raw::c_int,
        bStart: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetSerialNumber(
        iCameraID: ::std::os::raw::c_int,
        pSN: *mut ASI_SN,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASISetTriggerOutputIOConf(
        iCameraID: ::std::os::raw::c_int,
        pin: ASI_TRIG_OUTPUT_PIN,
        bPinHigh: ::std::os::raw::c_int,
        lDelay: ::std::os::raw::c_long,
        lDuration: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGetTriggerOutputIOConf(
        iCameraID: ::std::os::raw::c_int,
        pin: ASI_TRIG_OUTPUT_PIN,
        bPinHigh: *mut ::std::os::raw::c_int,
        lDelay: *mut ::std::os::raw::c_long,
        lDuration: *mut ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ASIGPSGetData(
        iCameraID: ::std::os::raw::c_int,
        startLineGPSData: *mut ASI_GPS_DATA,
        endLineGPSData: *mut ASI_GPS_DATA,
    ) -> ::std::os::raw::c_int;
}
