#![allow(dead_code)]

use std::os::raw::c_void;

pub const QHYCCD_SUCCESS: u32 = 0;
pub const QHYCCD_ERROR: u32 = 0xFFFFFFFF;
pub const QHYCCD_READ_DIRECTLY: u32 = 0x2000;

pub type QhyccdHandle = *mut c_void;

#[allow(clippy::upper_case_acronyms)]
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ControlId {
    Brightness = 0,
    Contrast = 1,
    Wbr = 2,
    Wbb = 3,
    Wbg = 4,
    Gamma = 5,
    Gain = 6,
    Offset = 7,
    Exposure = 8,
    Speed = 9,
    TransferBit = 10,
    Channels = 11,
    UsbTraffic = 12,
    RowDeNoise = 13,
    CurTemp = 14,
    CurPWM = 15,
    ManualPWM = 16,
    CfwPort = 17,
    Cooler = 18,
    St4Port = 19,
    CamColor = 20,
    CamBin1x1mode = 21,
    CamBin2x2mode = 22,
    CamBin3x3mode = 23,
    CamBin4x4mode = 24,
    CamMechanicalShutter = 25,
    CamTrigerInterface = 26,
    CamTecoverprotectInterface = 27,
    CamSignalClampInterface = 28,
    CamFinetoneInterface = 29,
    CamShutterMotorHeatingInterface = 30,
    CamCalibrateFpnInterface = 31,
    CamChipTemperatureSensorInterface = 32,
    CamUsbReadoutSlowestInterface = 33,
    Cam8bits = 34,
    Cam16bits = 35,
    CamGps = 36,
    CamIgnoreOverscanInterface = 37,
    Qhyccd3aAutoexposure = 39,
    Qhyccd3aAutofocus = 40,
    Ampv = 41,
    Vcam = 42,
    CamViewMode = 43,
    CfwSlotsNum = 44,
    IsExposingDone = 45,
    ScreenStretchB = 46,
    ScreenStretchW = 47,
    DDR = 48,
    CamLightPerformanceMode = 49,
    CamQhy5IIGuideMode = 50,
    DDRBufferCapacity = 51,
    DDRBufferReadThreshold = 52,
    DefaultGain = 53,
    DefaultOffset = 54,
    OutputDataActualBits = 55,
    OutputDataAlignment = 56,
    CamSingleFrameMode = 57,
    CamLiveVideoMode = 58,
    CamIsColor = 59,
    HasHardwareFrameCounter = 60,
    MaxIdError = 61,
    CamHumidity = 62,
    CamPressure = 63,
    VacuumPump = 64,
    SensorChamberCyclePump = 65,
    Cam32bits = 66,
    CamSensorUlvoStatus = 67,
    CamSensorPhaseReTrain = 68,
    CamInitConfigFromFlash = 69,
    CamTriggerMode = 70,
    CamTriggerOut = 71,
    CamBurstMode = 72,
    CamSpeakerLedAlarm = 73,
    CamWatchDogFpga = 74,
    CamBin6x6mode = 75,
    CamBin8x8mode = 76,
    CamGlobalSensorGpsLED = 77,
    ImgProc = 78,
    RemoveRbi = 79,
    GlobalReset = 80,
    FrameDetect = 81,
    CamGainDbConversion = 82,
    CamCurveSystemGain = 83,
    CamCurveFullWell = 84,
    CamCurveReadoutNoise = 85,
    MaxId = 86,
    Autowhitebalance = 1024,
    Autoexposure = 1025,
    AutoexpMessureValue = 1026,
    AutoexpMessureMethod = 1027,
    ImageStabilization = 1028,
    GaindB = 1029,
}
