/* automatically generated by rust-bindgen 0.72.1 from toupcam.h v59.31026.20260322
   then curated to only the types/constants needed by the night-amplifier integration. */
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code, clippy::upper_case_acronyms)]

use std::os::raw::{c_char, c_int, c_short, c_uint, c_ulonglong, c_ushort, c_void};

// ── HRESULT (Windows-style, >= 0 is success, < 0 is failure) ────────────────
pub type HRESULT = c_int;
pub const S_OK: u32 = 0;
pub const S_FALSE: u32 = 1;

// ── Handle ──────────────────────────────────────────────────────────────────
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Toupcam_t {
    pub unused: c_int,
}
pub type HToupcam = *mut Toupcam_t;

pub const TOUPCAM_MAX: u32 = 128;

// ── Capability flags (from ToupcamModelV2.flag, 64-bit) ─────────────────────
pub const TOUPCAM_FLAG_CMOS: u32 = 0x0000_0001;
pub const TOUPCAM_FLAG_MONO: u32 = 0x0000_0010;
pub const TOUPCAM_FLAG_BINSKIP_SUPPORTED: u32 = 0x0000_0020;
pub const TOUPCAM_FLAG_USB30: u32 = 0x0000_0040;
pub const TOUPCAM_FLAG_TEC: u32 = 0x0000_0080;
pub const TOUPCAM_FLAG_ST4: u32 = 0x0000_0200;
pub const TOUPCAM_FLAG_GETTEMPERATURE: u32 = 0x0000_0400;
pub const TOUPCAM_FLAG_RAW10: u32 = 0x0000_1000;
pub const TOUPCAM_FLAG_RAW12: u32 = 0x0000_2000;
pub const TOUPCAM_FLAG_RAW14: u32 = 0x0000_4000;
pub const TOUPCAM_FLAG_RAW16: u32 = 0x0000_8000;
pub const TOUPCAM_FLAG_FAN: u32 = 0x0001_0000;
pub const TOUPCAM_FLAG_TEC_ONOFF: u32 = 0x0002_0000;
pub const TOUPCAM_FLAG_RAW8: u32 = 0x8000_0000;
pub const TOUPCAM_FLAG_CG: u32 = 0x0400_0000;
pub const TOUPCAM_FLAG_TRIGGER_SOFTWARE: u32 = 0x0008_0000;
pub const TOUPCAM_FLAG_TRIGGER_EXTERNAL: u32 = 0x0010_0000;

// ── Event codes (for pull-mode callback) ────────────────────────────────────
pub const TOUPCAM_EVENT_EXPOSURE: u32 = 0x0001;
pub const TOUPCAM_EVENT_TEMPTINT: u32 = 0x0002;
pub const TOUPCAM_EVENT_IMAGE: u32 = 0x0004;
pub const TOUPCAM_EVENT_STILLIMAGE: u32 = 0x0005;
pub const TOUPCAM_EVENT_ERROR: u32 = 0x0080;
pub const TOUPCAM_EVENT_DISCONNECTED: u32 = 0x0081;
pub const TOUPCAM_EVENT_NOFRAMETIMEOUT: u32 = 0x0082;

// ── Option IDs (for put_Option / get_Option) ────────────────────────────────
pub const TOUPCAM_OPTION_RAW: u32 = 0x04;
pub const TOUPCAM_OPTION_BITDEPTH: u32 = 0x06;
pub const TOUPCAM_OPTION_BINNING: u32 = 0x17;
pub const TOUPCAM_OPTION_TRIGGER: u32 = 0x0b;
pub const TOUPCAM_OPTION_UPSIDE_DOWN: u32 = 0x23;
pub const TOUPCAM_OPTION_FLUSH: u32 = 0x3d;
pub const TOUPCAM_OPTION_TEC: u32 = 0x08;
pub const TOUPCAM_OPTION_TECTARGET: u32 = 0x0f;

// ── Structs ─────────────────────────────────────────────────────────────────

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ToupcamResolution {
    pub width: c_uint,
    pub height: c_uint,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ToupcamModelV2 {
    pub name: *const c_char,
    pub flag: c_ulonglong,
    pub maxspeed: c_uint,
    pub preview: c_uint,
    pub still: c_uint,
    pub maxfanspeed: c_uint,
    pub ioctrol: c_uint,
    pub xpixsz: f32,
    pub ypixsz: f32,
    pub res: [ToupcamResolution; 16usize],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ToupcamDeviceV2 {
    pub displayname: [c_char; 64usize],
    pub id: [c_char; 64usize],
    pub model: *const ToupcamModelV2,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ToupcamFrameInfoV3 {
    pub width: c_uint,
    pub height: c_uint,
    pub flag: c_uint,
    pub seq: c_uint,
    pub timestamp: c_ulonglong,
    pub shutterseq: c_uint,
    pub expotime: c_uint,
    pub expogain: c_ushort,
    pub blacklevel: c_ushort,
}

// ── Callback type ───────────────────────────────────────────────────────────
pub type PTOUPCAM_EVENT_CALLBACK =
    Option<unsafe extern "C" fn(nEvent: c_uint, ctxEvent: *mut c_void)>;

// ── Bayer FourCC helpers ────────────────────────────────────────────────────

/// Build a FourCC from four ASCII chars (little-endian convention).
pub const fn make_fourcc(a: u8, b: u8, c: u8, d: u8) -> u32 {
    (a as u32) | ((b as u32) << 8) | ((c as u32) << 16) | ((d as u32) << 24)
}

pub const FOURCC_GBRG: u32 = make_fourcc(b'G', b'B', b'R', b'G');
pub const FOURCC_RGGB: u32 = make_fourcc(b'R', b'G', b'G', b'B');
pub const FOURCC_BGGR: u32 = make_fourcc(b'B', b'G', b'G', b'R');
pub const FOURCC_GRBG: u32 = make_fourcc(b'G', b'R', b'B', b'G');
pub const FOURCC_YYYY: u32 = make_fourcc(b'Y', b'Y', b'Y', b'Y');
